name: Playwright Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Create .env.test.local file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NEXT_PUBLIC_TEST_DB_URL: ${{ secrets.NEXT_PUBLIC_TEST_DB_URL }}
          envkey_TEST: "test-var"
          file_name: .env.test.local
      - name: Print env
        run: cat .env.test.local
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: npx playwright install
      - name: Run dev server
        run: yarn dev
      - name: Run e2e test
        run: yarn run test:e2e
